In [6]:
import pandas as pd
df = pd.read_csv("dataset_labelled_with_score.csv")

In [7]:
df

,bank_count_500m,bus_stop_count_500m,cinema_count_500m,clinic_count_500m,college_count_500m,hospital_count_500m,museum_count_500m,office_count_500m,parking_space_count_500m,recreation_count_500m,retail_count_500m,school_count_500m,temple_count_500m,competitor_count_500m,avg_restaurant_rating_500m,avg_review_ratings_500m,nearest_restaurant_m,place_id,latitude,longitude,search_area,primary_type,searched_as,label,office_count_500m_normalized,office_count_500m_contribution,retail_count_500m_normalized,retail_count_500m_contribution,parking_space_count_500m_normalized,parking_space_count_500m_contribution,recreation_count_500m_normalized,recreation_count_500m_contribution,bank_count_500m_normalized,bank_count_500m_contribution,bus_stop_count_500m_normalized,bus_stop_count_500m_contribution,college_count_500m_normalized,college_count_500m_contribution,hospital_count_500m_normalized,hospital_count_500m_contribution,school_count_500m_normalized,school_count_500m_contribution,cinema_count_500m_normalized,cinema_count_500m_contribution,museum_count_500m_normalized,museum_count_500m_contribution,temple_count_500m_normalized,temple_count_500m_contribution,clinic_count_500m_normalized,clinic_count_500m_contribution,nearest_restaurant_m_normalized,nearest_restaurant_m_contribution,competitor_count_500m_normalized,competitor_count_500m_contribution,avg_restaurant_rating_500m_normalized,avg_restaurant_rating_500m_contribution,avg_review_ratings_500m_normalized,avg_review_ratings_500m_contribution,feasibility_score,cluster,feasibility_label
0,26,1,0,44,22,9,1,54,5,21,52,35,15,20,4.265000,87.700000,66.357920,ChIJsZ5mY70Z6zkRRBczgL9a8ms,27.699546,85.337687,Baneshwor,restaurant,restaurant,1,0.524272,0.022053,0.329114,0.007984,0.217391,0.016110,0.272727,0.009656,0.273684,0.018875,0.090909,0.007885,0.343750,0.023808,0.290323,0.012063,0.583333,0.017102,0.000000,0.000000,0.027778,0.004460,0.144231,0.010072,0.578947,0.026628,0.015377,0.000851,0.837398,0.006476,0.183750,0.002125,0.941020,0.000377,18.652333,0,Moderate
1,43,4,1,46,37,13,1,66,6,16,80,40,13,44,4.247727,159.477273,3.883478,ChIJ5SO0EQ0Z6zkRTMnqUebrTqA,27.692262,85.336472,Baneshwor,restaurant,restaurant,1,0.640777,0.026953,0.506329,0.012284,0.260870,0.019332,0.207792,0.007357,0.452632,0.031216,0.363636,0.031538,0.578125,0.040041,0.419355,0.017424,0.666667,0.019545,0.142857,0.025274,0.027778,0.004460,0.125000,0.008729,0.605263,0.027838,0.000900,0.000050,0.642276,0.004967,0.188068,0.002175,0.892192,0.000357,27.954012,2,High
2,57,6,3,65,49,12,1,68,9,15,66,28,6,48,4.231250,201.104167,35.022157,ChIJTdMmLgAZ6zkR84zXOWwdgPE,27.689064,85.334295,Baneshwor,restaurant,restaurant,1,0.660194,0.027770,0.417722,0.010134,0.391304,0.028998,0.194805,0.006897,0.600000,0.041379,0.545455,0.047307,0.765625,0.053028,0.387097,0.016084,0.466667,0.013681,0.428571,0.075822,0.027778,0.004460,0.057692,0.004029,0.855263,0.039336,0.008116,0.000449,0.609756,0.004716,0.192187,0.002222,0.863875,0.000346,37.665885,2,High
3,5,0,0,23,6,4,0,66,4,26,78,16,17,14,4.371429,83.214286,5.217717,ChIJ3Ru72S8Z6zkR6JYG3tsYlGk,27.681549,85.341340,Baneshwor,restaurant,restaurant,1,0.640777,0.026953,0.493671,0.011976,0.173913,0.012888,0.337662,0.011955,0.052632,0.003630,0.000000,0.000000,0.093750,0.006493,0.129032,0.005361,0.266667,0.007818,0.000000,0.000000,0.000000,0.000000,0.163462,0.011414,0.302632,0.013919,0.001209,0.000067,0.886179,0.006854,0.157143,0.001817,0.944072,0.000378,12.152369,1,Low
4,55,6,3,66,46,11,1,65,10,15,64,27,7,47,4.270213,200.893617,35.022157,ChIJJbL_SlQZ6zkRFWSjunPmuVU,27.688812,85.334080,Baneshwor,restaurant,restaurant,1,0.631068,0.026545,0.405063,0.009827,0.434783,0.032220,0.194805,0.006897,0.578947,0.039927,0.545455,0.047307,0.718750,0.049781,0.354839,0.014744,0.450000,0.013193,0.428571,0.075822,0.027778,0.004460,0.067308,0.004700,0.868421,0.039942,0.008116,0.000449,0.617886,0.004779,0.182447,0.002110,0.864018,0.000346,37.304810,2,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4167,1,0,0,6,15,3,0,11,1,9,46,11,6,5,4.475000,15.000000,183.483099,BG_02695,27.684701,85.280811,Kirtipur,NaN,NaN,0,0.106796,0.004492,0.291139,0.007063,0.043478,0.003222,0.116883,0.004138,0.010526,0.000726,0.000000,0.000000,0.234375,0.016233,0.096774,0.004021,0.183333,0.005375,0.000000,0.000000,0.000000,0.000000,0.057692,0.004029,0.078947,0.003631,0.042519,0.002352,0.959350,0.007420,0.131250,0.001518,0.990476,0.000397,6.461612,1,Low
4168,0,1,0,0,20,1,0,0,0,8,8,1,1,0,4.410000,97.071429,523.445615,BG_02696,27.682025,85.287458,Kirtipur,NaN,NaN,0,0.000000,0.000000,0.050633,0.001228,0.000000,0.000000,0.103896,0.003678,0.000000,0.000000,0.090909,0.007885,0.312500,0.021644,0.032258,0.001340,0.016667,0.000489,0.000000,0.000000,0.000000,0.000000,0.009615,0.000671,0.000000,0.000000,0.121300,0.006711,1.000000,0.007734,0.147500,0.001705,0.934645,0.000374,5.346062,1,Low
4169,0,0,1,1,0,5,0,8,2,9,29,9,7,8,3.837500,79.250000,82.281163,BG_02697,27.670845,85.271484,Kirtipur,NaN,NaN,0,0.077670,0.003267,0.183544,0.004453,0.086957,0.006444,0.116883,0.004138,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.161290,0.006702,0.150000,0.004398,0.142857,0.025274,0.000000,0.000000,0.067308,0.004700,0.013158,0.000605,0.019067,0.001055,0.934959,0.007231,0.290625,0.003360,0.946769,0.000379,7.200596,1,Low
4170,0,0,0,0,1,1,0,0,0,6,0,0,3,1,4.700000,3.000000,423.140504,BG_02698,27.674436,85.290706,Kirtipur,NaN,NaN,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.077922,0.002759,0.000000,0.000000,0.000000,0.000000,0.015625,0.001082,0.032258,0.001340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.028846,0.002014,0.000000,0.000000,0.098056,0.005425,0.991870,0.007671,0.075000,0.000867,0.998639,0.000400,2.155904,1,Low
4171,14,3,0,18,9,7,2,11,2,14,48,12,17,32,4.207143,62.571429,125.644517,BG_02699,27.674736,85.282718,Kirtipur,NaN,NaN,0,0.106796,0.004492,0.303797,0.007370,0.086957,0.006444,0.181818,0.006437,0.147368,0.010163,0.272727,0.023654,0.140625,0.009740,0.225806,0.009382,0.200000,0.005863,0.000000,0.000000,0.055556,0.008921,0.163462,0.011414,0.236842,0.010893,0.029116,0.001611,0.739837,0.005722,0.198214,0.002292,0.958115,0.000384,12.478293,1,Low

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4172 entries, 0 to 4171
Data columns (total 61 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   bank_count_500m                          4172 non-null   int64
 1   bus_stop_count_500m                      4172 non-null   int64
 2   cinema_count_500m                        4172 non-null   int64
 3   clinic_count_500m                        4172 non-null   int64
 4   college_count_500m                       4172 non-null   int64
 5   hospital_count_500m                      4172 non-null   int64
 6   museum_count_500m                        4172 non-null   int64
 7   office_count_500m                        4172 non-null   int64
 8   parking_space_count_500m                 4172 non-null   int64
 9   recreation_count_500m                    4172 non-null   int64
 10  retail_count_500m                        4172 non-null   int64
 11  school_count_500m                        4172 non-null   int64
 12  temple_count_500m                        4172 non-null   int64
 13  competitor_count_500m                    4172 non-null   int64
 14  avg_restaurant_rating_500m               4172 non-null   float64
 15  avg_review_ratings_500m                  4172 non-null   float64
 16  nearest_restaurant_m                     4172 non-null   float64
 17  place_id                                 4172 non-null   object
 18  latitude                                 4172 non-null   float64
 19  longitude                                4172 non-null   float64
 20  search_area                              4172 non-null   object
 21  primary_type                             1466 non-null   object
 22  searched_as                              1472 non-null   object
 23  label                                    4172 non-null   int64
 24  office_count_500m_normalized             4172 non-null   float64
 25  office_count_500m_contribution           4172 non-null   float64
 26  retail_count_500m_normalized             4172 non-null   float64
 27  retail_count_500m_contribution           4172 non-null   float64
 28  parking_space_count_500m_normalized      4172 non-null   float64
 29  parking_space_count_500m_contribution    4172 non-null   float64
 30  recreation_count_500m_normalized         4172 non-null   float64
 31  recreation_count_500m_contribution       4172 non-null   float64
 32  bank_count_500m_normalized               4172 non-null   float64
 33  bank_count_500m_contribution             4172 non-null   float64
 34  bus_stop_count_500m_normalized           4172 non-null   float64
 35  bus_stop_count_500m_contribution         4172 non-null   float64
 36  college_count_500m_normalized            4172 non-null   float64
 37  college_count_500m_contribution          4172 non-null   float64
 38  hospital_count_500m_normalized           4172 non-null   float64
 39  hospital_count_500m_contribution         4172 non-null   float64
 40  school_count_500m_normalized             4172 non-null   float64
 41  school_count_500m_contribution           4172 non-null   float64
 42  cinema_count_500m_normalized             4172 non-null   float64
 43  cinema_count_500m_contribution           4172 non-null   float64
 44  museum_count_500m_normalized             4172 non-null   float64
 45  museum_count_500m_contribution           4172 non-null   float64
 46  temple_count_500m_normalized             4172 non-null   float64
 47  temple_count_500m_contribution           4172 non-null   float64
 48  clinic_count_500m_normalized             4172 non-null   float64
 49  clinic_count_500m_contribution           4172 non-null   float64
 50  nearest_restaurant_m_normalized          4172 non-null   float64
 51  nearest_restaurant_m_contribution        4172 non-null   float64
 52  competitor_count_500m_normalized         4172 non-null   float64
 53  competitor_count_500m_contribution       4172 non-null   float64
 54  avg_restaurant_rating_500m_normalized    4172 non-null   float64
 55  avg_restaurant_rating_500m_contribution  4172 non-null   float64
 56  avg_review_ratings_500m_normalized       4172 non-null   float64
 57  avg_review_ratings_500m_contribution     4172 non-null   float64
 58  feasibility_score                        4172 non-null   float64
 59  cluster                                  4172 non-null   int64
 60  feasibility_label                        4172 non-null   object
dtypes: float64(40), int64(16), object(5)
memory usage: 1.9+ MB

In [9]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

df

,bank_count_500m,bus_stop_count_500m,cinema_count_500m,clinic_count_500m,college_count_500m,hospital_count_500m,museum_count_500m,office_count_500m,parking_space_count_500m,recreation_count_500m,retail_count_500m,school_count_500m,temple_count_500m,competitor_count_500m,avg_restaurant_rating_500m,avg_review_ratings_500m,nearest_restaurant_m,place_id,latitude,longitude,search_area,primary_type,searched_as,label,office_count_500m_normalized,office_count_500m_contribution,retail_count_500m_normalized,retail_count_500m_contribution,parking_space_count_500m_normalized,parking_space_count_500m_contribution,recreation_count_500m_normalized,recreation_count_500m_contribution,bank_count_500m_normalized,bank_count_500m_contribution,bus_stop_count_500m_normalized,bus_stop_count_500m_contribution,college_count_500m_normalized,college_count_500m_contribution,hospital_count_500m_normalized,hospital_count_500m_contribution,school_count_500m_normalized,school_count_500m_contribution,cinema_count_500m_normalized,cinema_count_500m_contribution,museum_count_500m_normalized,museum_count_500m_contribution,temple_count_500m_normalized,temple_count_500m_contribution,clinic_count_500m_normalized,clinic_count_500m_contribution,nearest_restaurant_m_normalized,nearest_restaurant_m_contribution,competitor_count_500m_normalized,competitor_count_500m_contribution,avg_restaurant_rating_500m_normalized,avg_restaurant_rating_500m_contribution,avg_review_ratings_500m_normalized,avg_review_ratings_500m_contribution,feasibility_score,cluster,feasibility_label
0,26,1,0,44,22,9,1,54,5,21,52,35,15,20,4.265000,87.700000,66.357920,ChIJsZ5mY70Z6zkRRBczgL9a8ms,27.699546,85.337687,Baneshwor,restaurant,restaurant,1,0.524272,0.022053,0.329114,0.007984,0.217391,0.016110,0.272727,0.009656,0.273684,0.018875,0.090909,0.007885,0.343750,0.023808,0.290323,0.012063,0.583333,0.017102,0.000000,0.000000,0.027778,0.004460,0.144231,0.010072,0.578947,0.026628,0.015377,0.000851,0.837398,0.006476,0.183750,0.002125,0.941020,0.000377,18.652333,0,Moderate
1,43,4,1,46,37,13,1,66,6,16,80,40,13,44,4.247727,159.477273,3.883478,ChIJ5SO0EQ0Z6zkRTMnqUebrTqA,27.692262,85.336472,Baneshwor,restaurant,restaurant,1,0.640777,0.026953,0.506329,0.012284,0.260870,0.019332,0.207792,0.007357,0.452632,0.031216,0.363636,0.031538,0.578125,0.040041,0.419355,0.017424,0.666667,0.019545,0.142857,0.025274,0.027778,0.004460,0.125000,0.008729,0.605263,0.027838,0.000900,0.000050,0.642276,0.004967,0.188068,0.002175,0.892192,0.000357,27.954012,2,High
2,57,6,3,65,49,12,1,68,9,15,66,28,6,48,4.231250,201.104167,35.022157,ChIJTdMmLgAZ6zkR84zXOWwdgPE,27.689064,85.334295,Baneshwor,restaurant,restaurant,1,0.660194,0.027770,0.417722,0.010134,0.391304,0.028998,0.194805,0.006897,0.600000,0.041379,0.545455,0.047307,0.765625,0.053028,0.387097,0.016084,0.466667,0.013681,0.428571,0.075822,0.027778,0.004460,0.057692,0.004029,0.855263,0.039336,0.008116,0.000449,0.609756,0.004716,0.192187,0.002222,0.863875,0.000346,37.665885,2,High
3,5,0,0,23,6,4,0,66,4,26,78,16,17,14,4.371429,83.214286,5.217717,ChIJ3Ru72S8Z6zkR6JYG3tsYlGk,27.681549,85.341340,Baneshwor,restaurant,restaurant,1,0.640777,0.026953,0.493671,0.011976,0.173913,0.012888,0.337662,0.011955,0.052632,0.003630,0.000000,0.000000,0.093750,0.006493,0.129032,0.005361,0.266667,0.007818,0.000000,0.000000,0.000000,0.000000,0.163462,0.011414,0.302632,0.013919,0.001209,0.000067,0.886179,0.006854,0.157143,0.001817,0.944072,0.000378,12.152369,1,Low
4,55,6,3,66,46,11,1,65,10,15,64,27,7,47,4.270213,200.893617,35.022157,ChIJJbL_SlQZ6zkRFWSjunPmuVU,27.688812,85.334080,Baneshwor,restaurant,restaurant,1,0.631068,0.026545,0.405063,0.009827,0.434783,0.032220,0.194805,0.006897,0.578947,0.039927,0.545455,0.047307,0.718750,0.049781,0.354839,0.014744,0.450000,0.013193,0.428571,0.075822,0.027778,0.004460,0.067308,0.004700,0.868421,0.039942,0.008116,0.000449,0.617886,0.004779,0.182447,0.002110,0.864018,0.000346,37.304810,2,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4167,1,0,0,6,15,3,0,11,1,9,46,11,6,5,4.475000,15.000000,183.483099,BG_02695,27.684701,85.280811,Kirtipur,NaN,NaN,0,0.106796,0.004492,0.291139,0.007063,0.043478,0.003222,0.116883,0.004138,0.010526,0.000726,0.000000,0.000000,0.234375,0.016233,0.096774,0.004021,0.183333,0.005375,0.000000,0.000000,0.000000,0.000000,0.057692,0.004029,0.078947,0.003631,0.042519,0.002352,0.959350,0.007420,0.131250,0.001518,0.990476,0.000397,6.461612,1,Low
4168,0,1,0,0,20,1,0,0,0,8,8,1,1,0,4.410000,97.071429,523.445615,BG_02696,27.682025,85.287458,Kirtipur,NaN,NaN,0,0.000000,0.000000,0.050633,0.001228,0.000000,0.000000,0.103896,0.003678,0.000000,0.000000,0.090909,0.007885,0.312500,0.021644,0.032258,0.001340,0.016667,0.000489,0.000000,0.000000,0.000000,0.000000,0.009615,0.000671,0.000000,0.000000,0.121300,0.006711,1.000000,0.007734,0.147500,0.001705,0.934645,0.000374,5.346062,1,Low
4169,0,0,1,1,0,5,0,8,2,9,29,9,7,8,3.837500,79.250000,82.281163,BG_02697,27.670845,85.271484,Kirtipur,NaN,NaN,0,0.077670,0.003267,0.183544,0.004453,0.086957,0.006444,0.116883,0.004138,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.161290,0.006702,0.150000,0.004398,0.142857,0.025274,0.000000,0.000000,0.067308,0.004700,0.013158,0.000605,0.019067,0.001055,0.934959,0.007231,0.290625,0.003360,0.946769,0.000379,7.200596,1,Low
4170,0,0,0,0,1,1,0,0,0,6,0,0,3,1,4.700000,3.000000,423.140504,BG_02698,27.674436,85.290706,Kirtipur,NaN,NaN,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.077922,0.002759,0.000000,0.000000,0.000000,0.000000,0.015625,0.001082,0.032258,0.001340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.028846,0.002014,0.000000,0.000000,0.098056,0.005425,0.991870,0.007671,0.075000,0.000867,0.998639,0.000400,2.155904,1,Low
4171,14,3,0,18,9,7,2,11,2,14,48,12,17,32,4.207143,62.571429,125.644517,BG_02699,27.674736,85.282718,Kirtipur,NaN,NaN,0,0.106796,0.004492,0.303797,0.007370,0.086957,0.006444,0.181818,0.006437,0.147368,0.010163,0.272727,0.023654,0.140625,0.009740,0.225806,0.009382,0.200000,0.005863,0.000000,0.000000,0.055556,0.008921,0.163462,0.011414,0.236842,0.010893,0.029116,0.001611,0.739837,0.005722,0.198214,0.002292,0.958115,0.000384,12.478293,1,Low

In [16]:
meta_cols = [
    "place_id",
    "latitude",
    "longitude",
    "search_area",
    "primary_type",
    "searched_as",
    "label",
]

score_cols = [
    "bank_count_500m",
    "bus_stop_count_500m",
    "cinema_count_500m",
    "clinic_count_500m",
    "college_count_500m",
    "hospital_count_500m",
    "museum_count_500m",
    "office_count_500m",
    "parking_space_count_500m",
    "recreation_count_500m",
    "retail_count_500m",
    "school_count_500m",
    "temple_count_500m",
    "nearest_restaurant_m",
    "competitor_count_500m",
    "avg_restaurant_rating_500m",
    "avg_review_ratings_500m",
]

result_cols = [
    "feasibility_score",
    "feasibility_label",
    "cluster",
]

ordered_cols = meta_cols + result_cols

for col in score_cols:
    ordered_cols.extend([
        col,
        f"{col}_normalized",
        f"{col}_contribution",
    ])

other_cols = [col for col in df.columns if col not in ordered_cols]

df = df[ordered_cols + other_cols]

In [17]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

df

,place_id,latitude,longitude,search_area,primary_type,searched_as,label,feasibility_score,feasibility_label,cluster,bank_count_500m,bank_count_500m_normalized,bank_count_500m_contribution,bus_stop_count_500m,bus_stop_count_500m_normalized,bus_stop_count_500m_contribution,cinema_count_500m,cinema_count_500m_normalized,cinema_count_500m_contribution,clinic_count_500m,clinic_count_500m_normalized,clinic_count_500m_contribution,college_count_500m,college_count_500m_normalized,college_count_500m_contribution,hospital_count_500m,hospital_count_500m_normalized,hospital_count_500m_contribution,museum_count_500m,museum_count_500m_normalized,museum_count_500m_contribution,office_count_500m,office_count_500m_normalized,office_count_500m_contribution,parking_space_count_500m,parking_space_count_500m_normalized,parking_space_count_500m_contribution,recreation_count_500m,recreation_count_500m_normalized,recreation_count_500m_contribution,retail_count_500m,retail_count_500m_normalized,retail_count_500m_contribution,school_count_500m,school_count_500m_normalized,school_count_500m_contribution,temple_count_500m,temple_count_500m_normalized,temple_count_500m_contribution,nearest_restaurant_m,nearest_restaurant_m_normalized,nearest_restaurant_m_contribution,competitor_count_500m,competitor_count_500m_normalized,competitor_count_500m_contribution,avg_restaurant_rating_500m,avg_restaurant_rating_500m_normalized,avg_restaurant_rating_500m_contribution,avg_review_ratings_500m,avg_review_ratings_500m_normalized,avg_review_ratings_500m_contribution
0,ChIJsZ5mY70Z6zkRRBczgL9a8ms,27.699546,85.337687,Baneshwor,restaurant,restaurant,1,18.652333,Moderate,0,26,0.273684,0.018875,1,0.090909,0.007885,0,0.000000,0.000000,44,0.578947,0.026628,22,0.343750,0.023808,9,0.290323,0.012063,1,0.027778,0.004460,54,0.524272,0.022053,5,0.217391,0.016110,21,0.272727,0.009656,52,0.329114,0.007984,35,0.583333,0.017102,15,0.144231,0.010072,66.357920,0.015377,0.000851,20,0.837398,0.006476,4.265000,0.183750,0.002125,87.700000,0.941020,0.000377
1,ChIJ5SO0EQ0Z6zkRTMnqUebrTqA,27.692262,85.336472,Baneshwor,restaurant,restaurant,1,27.954012,High,2,43,0.452632,0.031216,4,0.363636,0.031538,1,0.142857,0.025274,46,0.605263,0.027838,37,0.578125,0.040041,13,0.419355,0.017424,1,0.027778,0.004460,66,0.640777,0.026953,6,0.260870,0.019332,16,0.207792,0.007357,80,0.506329,0.012284,40,0.666667,0.019545,13,0.125000,0.008729,3.883478,0.000900,0.000050,44,0.642276,0.004967,4.247727,0.188068,0.002175,159.477273,0.892192,0.000357
2,ChIJTdMmLgAZ6zkR84zXOWwdgPE,27.689064,85.334295,Baneshwor,restaurant,restaurant,1,37.665885,High,2,57,0.600000,0.041379,6,0.545455,0.047307,3,0.428571,0.075822,65,0.855263,0.039336,49,0.765625,0.053028,12,0.387097,0.016084,1,0.027778,0.004460,68,0.660194,0.027770,9,0.391304,0.028998,15,0.194805,0.006897,66,0.417722,0.010134,28,0.466667,0.013681,6,0.057692,0.004029,35.022157,0.008116,0.000449,48,0.609756,0.004716,4.231250,0.192187,0.002222,201.104167,0.863875,0.000346
3,ChIJ3Ru72S8Z6zkR6JYG3tsYlGk,27.681549,85.341340,Baneshwor,restaurant,restaurant,1,12.152369,Low,1,5,0.052632,0.003630,0,0.000000,0.000000,0,0.000000,0.000000,23,0.302632,0.013919,6,0.093750,0.006493,4,0.129032,0.005361,0,0.000000,0.000000,66,0.640777,0.026953,4,0.173913,0.012888,26,0.337662,0.011955,78,0.493671,0.011976,16,0.266667,0.007818,17,0.163462,0.011414,5.217717,0.001209,0.000067,14,0.886179,0.006854,4.371429,0.157143,0.001817,83.214286,0.944072,0.000378
4,ChIJJbL_SlQZ6zkRFWSjunPmuVU,27.688812,85.334080,Baneshwor,restaurant,restaurant,1,37.304810,High,2,55,0.578947,0.039927,6,0.545455,0.047307,3,0.428571,0.075822,66,0.868421,0.039942,46,0.718750,0.049781,11,0.354839,0.014744,1,0.027778,0.004460,65,0.631068,0.026545,10,0.434783,0.032220,15,0.194805,0.006897,64,0.405063,0.009827,27,0.450000,0.013193,7,0.067308,0.004700,35.022157,0.008116,0.000449,47,0.617886,0.004779,4.270213,0.182447,0.002110,200.893617,0.864018,0.000346
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4167,BG_02695,27.684701,85.280811,Kirtipur,NaN,NaN,0,6.461612,Low,1,1,0.010526,0.000726,0,0.000000,0.000000,0,0.000000,0.000000,6,0.078947,0.003631,15,0.234375,0.016233,3,0.096774,0.004021,0,0.000000,0.000000,11,0.106796,0.004492,1,0.043478,0.003222,9,0.116883,0.004138,46,0.291139,0.007063,11,0.183333,0.005375,6,0.057692,0.004029,183.483099,0.042519,0.002352,5,0.959350,0.007420,4.475000,0.131250,0.001518,15.000000,0.990476,0.000397
4168,BG_02696,27.682025,85.287458,Kirtipur,NaN,NaN,0,5.346062,Low,1,0,0.000000,0.000000,1,0.090909,0.007885,0,0.000000,0.000000,0,0.000000,0.000000,20,0.312500,0.021644,1,0.032258,0.001340,0,0.000000,0.000000,0,0.000000,0.000000,0,0.000000,0.000000,8,0.103896,0.003678,8,0.050633,0.001228,1,0.016667,0.000489,1,0.009615,0.000671,523.445615,0.121300,0.006711,0,1.000000,0.007734,4.410000,0.147500,0.001705,97.071429,0.934645,0.000374
4169,BG_02697,27.670845,85.271484,Kirtipur,NaN,NaN,0,7.200596,Low,1,0,0.000000,0.000000,0,0.000000,0.000000,1,0.142857,0.025274,1,0.013158,0.000605,0,0.000000,0.000000,5,0.161290,0.006702,0,0.000000,0.000000,8,0.077670,0.003267,2,0.086957,0.006444,9,0.116883,0.004138,29,0.183544,0.004453,9,0.150000,0.004398,7,0.067308,0.004700,82.281163,0.019067,0.001055,8,0.934959,0.007231,3.837500,0.290625,0.003360,79.250000,0.946769,0.000379
4170,BG_02698,27.674436,85.290706,Kirtipur,NaN,NaN,0,2.155904,Low,1,0,0.000000,0.000000,0,0.000000,0.000000,0,0.000000,0.000000,0,0.000000,0.000000,1,0.015625,0.001082,1,0.032258,0.001340,0,0.000000,0.000000,0,0.000000,0.000000,0,0.000000,0.000000,6,0.077922,0.002759,0,0.000000,0.000000,0,0.000000,0.000000,3,0.028846,0.002014,423.140504,0.098056,0.005425,1,0.991870,0.007671,4.700000,0.075000,0.000867,3.000000,0.998639,0.000400
4171,BG_02699,27.674736,85.282718,Kirtipur,NaN,NaN,0,12.478293,Low,1,14,0.147368,0.010163,3,0.272727,0.023654,0,0.000000,0.000000,18,0.236842,0.010893,9,0.140625,0.009740,7,0.225806,0.009382,2,0.055556,0.008921,11,0.106796,0.004492,2,0.086957,0.006444,14,0.181818,0.006437,48,0.303797,0.007370,12,0.200000,0.005863,17,0.163462,0.011414,125.644517,0.029116,0.001611,32,0.739837,0.005722,4.207143,0.198214,0.002292,62.571429,0.958115,0.000384

In [18]:
df = df[ordered_cols + other_cols]

df.to_csv("dataset_labelled_with_score.csv", index=False)